export const system = {
  NOTIFICATION_LEAVING_TIMEOUT: 300,
  MODALS_BASE_Z_INDEX: 1000,
  MODALS_LEAVING_TIMEOUT: 200,
  NOTIFICATIONS_BASE_Z_INDEX: 1001,
  MODALS_SHAKING_TIMEOUT: 500,
} as const;
